export enum UserRole {
  ADMIN = "ADMIN",
  CREATOR = "CREATOR",
  RECOMMENDER = "RECOMMENDER",
  APPROVER = "APPROVER",
  DECISION_OWNER = "DECISION_OWNER",
  PERFORMER = "PERFORMER",
  AUDITOR = "AUDITOR",
}

export enum DocumentStatus {
  DRAFT = "DRAFT",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  SUBMITTED = "SUBMITTED",
  AWAITING_AGREEMENT = "AWAITING_AGREEMENT",
  NEEDS_CHANGES = "NEEDS_CHANGES",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  FINALIZED = "FINALIZED",
  EXECUTION_COMPLETE = "EXECUTION_COMPLETE",
  ARCHIVED = "ARCHIVED",
}

export enum RiskLevel {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum RapidRoleType {
  RECOMMEND = "RECOMMEND",
  AGREE = "AGREE",
  PERFORM = "PERFORM",
  INPUT = "INPUT",
  DECIDE = "DECIDE",
}

export enum ApprovalStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
}
